### ISSUE TITLE
Transfer project to server architecture

### ISSUE THREAD

**Issue by Alt004** [kxkw/chatgpt-telegram-bot#6]
We need a working 24/7 bot, so we must host this project on server

**Comment by kxkw** [comment]
@Alt004 i agree boss! Got a little bit more features to implement, and after that we'll definetly host it on remote server

**Comment by Alt004** [comment]
@kxkw Good job, nice work! Working like a clock

**Comment by kxkw** [comment]
@Alt004 thanks boss!
