### ISSUE TITLE
Implement logging

### ISSUE THREAD

**Issue by Arcadiyyyyyyyy** [kxkw/chatgpt-telegram-bot#8]

**Comment by Arcadiyyyyyyyy** [comment]
The "logging" module should be implemented. This will allow to save all code errors without unnesessary print() lines

**Comment by kxkw** [comment]
I'm not sure if I get it right. Can you please show some code examples or maybe a pull request with full code for the issue? 

Just keep in mind that all code additions should improve on the code and/or user experience, not damage it's utility/readability in any way
